[2023-03-28T06:15:13.581+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.run_bash2 scheduled__2023-03-27T06:00:00+00:00 [queued]>
[2023-03-28T06:15:13.744+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.run_bash2 scheduled__2023-03-27T06:00:00+00:00 [queued]>
[2023-03-28T06:15:13.745+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T06:15:13.745+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T06:15:13.745+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T06:15:13.877+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): run_bash2> on 2023-03-27 06:00:00+00:00
[2023-03-28T06:15:13.898+0000] {standard_task_runner.py:55} INFO - Started process 428 to run task
[2023-03-28T06:15:13.913+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'run_bash2', 'scheduled__2023-03-27T06:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp5d6w3_35']
[2023-03-28T06:15:13.914+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask run_bash2
[2023-03-28T06:15:15.713+0000] {task_command.py:388} INFO - Running <TaskInstance: test.run_bash2 scheduled__2023-03-27T06:00:00+00:00 [running]> on host 9119afc303d7
[2023-03-28T06:15:17.815+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=run_bash2
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T06:00:00+00:00
[2023-03-28T06:15:17.817+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-28T06:15:17.818+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'start data processing']
[2023-03-28T06:15:17.855+0000] {subprocess.py:86} INFO - Output:
[2023-03-28T06:15:17.858+0000] {subprocess.py:93} INFO - /bin/bash: line 1: start: command not found
[2023-03-28T06:15:17.859+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-28T06:15:18.252+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-28T06:15:18.308+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=test, task_id=run_bash2, execution_date=20230327T060000, start_date=20230328T061513, end_date=20230328T061518
[2023-03-28T06:15:18.427+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 71 for task run_bash2 (Bash command failed. The command returned a non-zero exit code 127.; 428)
[2023-03-28T06:15:18.478+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T06:15:18.823+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
